### ISSUE TITLE
Initial roadmap

### ISSUE THREAD

**Issue by emoralesb05** [Teradata/covalent-electron#5]
First things to tackle for electron:

- [ ] Create `covalent-electron-quickstart` with scripts for deployment.
- [ ] Make `covalent-electron` repo only for docs and `electron` module (utilities, db conn, helper classes, etc etc).
- [x] Auto reload code after modification for faster dev. (`electron-reload`).
- [x] Try to load/save a file from OS in ng2 app.
- [x] Try to make a `jdbc` connection and call a query.
- [ ] Check localStorage.
- [ ] Make endpoints configurable after packaging  (check for versioning).
- [ ] `offline`  vs `online` usages (like slack).
- [x] Add Monaco Editor (VSCode)
- [x] Add File-select component and load files in Monaco-editor

**Comment by kyleledbetter** [comment]
can probably make a wiki out of this https://github.com/Teradata/covalent-electron/wiki
